## 共用配置，由于所有服务都整合了Sleuth，所以将其放在这里。
sleuth:
    sampler:
      # 默认是0.1，生产中强烈建议删除这一行。
      percentage: 1.0

spring:
  cloud:
    consul:
      discovery:
        # 指定实例ID，如果不指定，那么默认是：${spring.application.name}:comma,separated,profiles:${server.port}
        # 这意味着：如果没指定profile，那么多个实例的instance-id都是应用名称-端口，实例ID就会相同
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        # 指定健康检查路径
        health-check-path: /actuator/health
        # 多久检查一次，例如：15s、1m
        health-check-interval: 15s
        prefer-ip-address: true
      host: consul
      port: 8500
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# 必须加上这部分配置，feign的Hystrix特性将无法生效
feign:
  hystrix:
    enabled: true


