spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms-content?useUnicode=true&useSSL=false&zeroDateTimeBehavior=round&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mscontent
    password: mscontent

keycloak:
  # keycloak地址
  auth-server-url: http://localhost:8080/auth
  # keycloak realm
  realm: realm
  resource: ms-content-sample
  securityConstraints:
  - authRoles:
    # 以下路径需要user-role角色才能访问
    - user-role
    securityCollections:
    # name可以随便写
    - name: user-role-mappings
      patterns:
      - /articles